using Newtonsoft.Json;
using DLLCreateScheduleExcel.Services;

namespace DLLCreateScheduleExcel.Entities
{
    public partial class Welcome
    {
        [JsonProperty("nomeDaTabela")]
        public string NomeDaTabela { get; set; }

        [JsonProperty("colunas")]
        public Coluna[] Colunas { get; set; }

        [JsonProperty("linhas")]
        public Linha[] Linhas { get; set; }

        [JsonProperty("dataInicio")]
        public string DataInicio { get; set; }

        [JsonProperty("dataFim")]
        public string DataFim { get; set; }
    }

    public partial class Welcome
    {
        public static Welcome[] FromJson(string json) => JsonConvert.DeserializeObject<Welcome[]>(json, Converter.Settings);
    }

    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using QuickType;
    //
    //    var welcome = Welcome.FromJson(jsonString);

}
